### ISSUE TITLE
微信登录的uin填什么

### ISSUE THREAD

**Issue by go1em** [Tigaisgzy/QQmusic-download#1]
微信扫码登录的，填关联的qq号好象不行

**Comment by go1em** [comment]
总是报这个错
```
Traceback (most recent call last):
  File "E:\Documents\code\QQmusic-download\QQ音乐V0.1\main.py", line 18, in <module>
    song_id, song_mid = search.get_song_id_and_mid(song_name=song_name, uin=uin)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Documents\code\QQmusic-download\QQ音乐V0.1\searchSong.py", line 60, in get_song_id_and_mid
    sign = execjs.compile(js).call('main', '')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\*****\AppData\Local\Programs\Python\Python312\Lib\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\*****\AppData\Local\Programs\Python\Python312\Lib\site-packages\execjs\_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\*****\AppData\Local\Programs\Python\Python312\Lib\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\*****\AppData\Local\Programs\Python\Python312\Lib\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\*****\AppData\Local\Programs\Python\Python312\Lib\site-packages\execjs\_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\*****\AppData\Local\Programs\Python\Python312\Lib\site-packages\execjs\_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: SyntaxError: 缺少标识符

E:\Documents\code\QQmusic-download\QQ音乐V0.1>
```
试着改了一下，搞不定

**Comment by Tigaisgzy** [comment]
微信登录的话，uin是cookie里面的wxuin

**Comment by go1em** [comment]
> 微信登录的话，uin是cookie里面的wxuin

是要改代码，在cookie中加一组wxuin，还是直接把值给uin呢？
另外上面的报错是怎么回事，能指教一下么，谢谢

**Comment by Tigaisgzy** [comment]
直接把值给uin，这个报错是语法错误，具体错误为“SyntaxError: 缺少标识符”，可能是漏写了某些关键字或标识符，或者代码格式不正确，再检查一下看看

**Comment by Tigaisgzy** [comment]
是微信登录的话，好像请求参数也有一些改变了，这个得自己研究下了，因为我基本不用微信登录
